# KNN

work with the titanic dataset

## 1
Fit a K-Nearest Neighbors classifier to your training sample and transform (i.e. make predictions on the training sample)

In [10]:
import pandas as pd
import numpy as np
import acquire
from prepare import prep_titanic
from prepare import my_train_test_split

In [11]:
df = prep_titanic()

In [12]:
df

passenger_id  survived  pclass     sex  sibsp  parch     fare  \
0               0         0       3    male      1      0   7.2500   
1               1         1       1  female      1      0  71.2833   
2               2         1       3  female      0      0   7.9250   
3               3         1       1  female      1      0  53.1000   
4               4         0       3    male      0      0   8.0500   
..            ...       ...     ...     ...    ...    ...      ...   
886           886         0       2    male      0      0  13.0000   
887           887         1       1  female      0      0  30.0000   
888           888         0       3  female      1      2  23.4500   
889           889         1       1    male      0      0  30.0000   
890           890         0       3    male      0      0   7.7500   

     embark_town  alone  sex_male  embark_town_Queenstown  \
0    Southampton      0         1                       0   
1      Cherbourg      0         0                       0   
2    Southampton      1         0                       0   
3    Southampton      0         0                       0   
4    Southampton      1         1                       0   
..           ...    ...       ...                     ...   
886  Southampton      1         1                       0   
887  Southampton      1         0                       0   
888  Southampton      0         0                       0   
889    Cherbourg      1         1                       0   
890   Queenstown      1         1                       1   

     embark_town_Southampton  
0                          1  
1                          0  
2                          1  
3                          1  
4                          1  
..                       ...  
886                        1  
887                        1  
888                        1  
889                        0  
890                        0  

[891 rows x 12 columns]

In [13]:
my_train_test_split(df, target='survived')

(     passenger_id  survived  pclass     sex  sibsp  parch      fare  \
 455           455         1       3    male      0      0    7.8958   
 380           380         1       1  female      0      0  227.5250   
 492           492         0       1    male      0      0   30.5000   
 55             55         1       1    male      0      0   35.5000   
 243           243         0       3    male      0      0    7.1250   
 ..            ...       ...     ...     ...    ...    ...       ...   
 695           695         0       2    male      0      0   13.5000   
 128           128         1       3  female      1      1   22.3583   
 636           636         0       3    male      0      0    7.9250   
 222           222         0       3    male      0      0    8.0500   
 496           496         1       1  female      1      0   78.2667   
 
      embark_town  alone  sex_male  embark_town_Queenstown  \
 455    Cherbourg      1         1                       0   
 380    Ch

In [16]:
train, validate, test = my_train_test_split(df, 'survived')

In [17]:
train.shape

(534, 12)

In [18]:
validate.shape

(178, 12)

In [19]:
test.shape

(179, 12)

create X & y version of train, where y is a series with just the target variable and X are all the features.

Object 	Description 	Purpose
1. df 	Dataframe, Features and target 	New features, additional cleaning needed, etc.
2. X_train 	Dataframe, Features 	Feature selection, fit models, make predictions
3. y_train 	Series, Target 	Feature selection, evaluate model predictions
4. X_validate 	Dataframe, Features 	Make predictions using top models
5. y_validate 	Series, Target 	Evaluate model predictions made from X_validate to assess overfitting
6. X_test 	Dataframe, Features 	Make predictions using best model
7. y_test 	Series, Target 	Evaluate model predictions made from X_test to estimate future performance on new data

In [30]:
# create split, dropping target
x_train = train.drop(columns=['survived','sex','embark_town'])
y_train = train.survived

x_val = validate.drop(columns=['survived','sex','embark_town'])
y_val = validate.survived

x_test = test.drop(columns=['survived','sex','embark_town'])
y_test = test.survived

# re-eval may be necc to drop more unnec. columns from split sets

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
knn = KNeighborsClassifier(n_neighbors=5)

fit model

In [31]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [34]:
import warnings
warnings.filterwarnings("ignore")

In [35]:
y_pred = knn.predict(x_train)

In [37]:
y_pred_proba = knn.predict_proba(x_train)

In [38]:
y_pred_proba

array([[0.6, 0.4],
       [0.4, 0.6],
       [0.8, 0.2],
       ...,
       [0.8, 0.2],
       [0.8, 0.2],
       [0. , 1. ]])

# 2
Evaluate your results using the model score, confusion matrix, and classification report.

# Eval. Model

In [39]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(x_train, y_train)))

Accuracy of KNN classifier on training set: 0.74


# Confusion Matrix

In [41]:
from sklearn.metrics import confusion_matrix

In [42]:
print(confusion_matrix(y_train, y_pred))

[[289  40]
 [ 99 106]]


# 3

Print and clearly label the following: Accuracy, true positive rate, false positive rate, true negative rate, false negative rate, precision, recall, f1-score, and support.

In [43]:
from sklearn.metrics import classification_report

In [44]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.88      0.81       329
           1       0.73      0.52      0.60       205

    accuracy                           0.74       534
   macro avg       0.74      0.70      0.71       534
weighted avg       0.74      0.74      0.73       534



# 4
Run through steps 1-3 setting k to 10

In [45]:
knn = KNeighborsClassifier(n_neighbors=10)

In [46]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [47]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(x_train, y_train)))

Accuracy of KNN classifier on training set: 0.71


In [48]:
print(confusion_matrix(y_train, y_pred))

[[289  40]
 [ 99 106]]


In [49]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.88      0.81       329
           1       0.73      0.52      0.60       205

    accuracy                           0.74       534
   macro avg       0.74      0.70      0.71       534
weighted avg       0.74      0.74      0.73       534



# 5
Run through steps 1-3 setting k to 20

In [50]:
knn = KNeighborsClassifier(n_neighbors=20)

In [51]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=20)

In [52]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(x_train, y_train)))

Accuracy of KNN classifier on training set: 0.68


In [53]:
print(classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.74      0.88      0.81       329
           1       0.73      0.52      0.60       205

    accuracy                           0.74       534
   macro avg       0.74      0.70      0.71       534
weighted avg       0.74      0.74      0.73       534



# 6
What are the differences in the evaluation metrics? Which performs better on your in-sample data? Why?

ANSWER:
The primary difference is the accuracy score, with k=5 having the highest accuracy and k=(n>5) decreasing as K increases.

# 7
Which model performs best on our out-of-sample data from validate?

In [54]:
knn = KNeighborsClassifier(n_neighbors=5)

In [69]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=10)

In [60]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(x_train, y_train)))
print('Accuracy of KNN classifier on validate set: {:.2f}'.format(knn.score(x_val, y_val)))

Accuracy of KNN classifier on training set: 0.74
Accuracy of KNN classifier on validate set: 0.58


In [63]:
y_pred = knn.predict(x_val)

In [65]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.69      0.67       110
           1       0.44      0.40      0.42        68

    accuracy                           0.58       178
   macro avg       0.55      0.54      0.54       178
weighted avg       0.57      0.58      0.57       178



test for k =10

In [66]:
knn = KNeighborsClassifier(n_neighbors=10)

In [70]:
print('Accuracy of KNN classifier on training set: {:.2f}'
     .format(knn.score(x_train, y_train)))
print('Accuracy of KNN classifier on validate set: {:.2f}'.format(knn.score(x_val, y_val)))

Accuracy of KNN classifier on training set: 0.71
Accuracy of KNN classifier on validate set: 0.59


In [67]:
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.65      0.69      0.67       110
           1       0.44      0.40      0.42        68

    accuracy                           0.58       178
   macro avg       0.55      0.54      0.54       178
weighted avg       0.57      0.58      0.57       178



Which model performs best on our out-of-sample data from validate?

ANSWER: k=5 performs best, highest accuracy with least difference between train & validate